### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ltackett** [ericvtheg/makid-public#1]
> [/u/RUUDIBOO](https://www.reddit.com/r/ableton/comments/17wcb5j/comment/k9gmgp1/)
> There are usually different categories of sessions that are always the same, so having specific tags would be great, maybe even instead of tiers - let the user set up their own tags to apply to sessions. Something like layout, programming, experiment, additional programming, mixing, multitrack export... Everyone has different workflows, so making them user generated would probably be the best

> [The Chainsmokers 2 (Steve)](https://discord.com/channels/1174557402268450876/1174750842121883648/1174921304915312690)
> Custom Fields or Tags(that you can also filter by)

![image](https://github.com/ericvtheg/makid-public/assets/12592/1d4f4ad8-5302-4e8b-9ef3-a44ec5b56c5a)

**Comment by ericvtheg** [comment]
Added in MAKID 0.1.3 🎉
