### ISSUE TITLE
[UI] Adding long statuses can push UI elements off screen

### ISSUE THREAD

**Issue by ltackett** [ericvtheg/makid-public#10]
**Environment**
* All

**Steps to repro**
1. Have at least one project listed
2. Write an absurdly long status

**Expected behavior**
* TBD

**Actual behavior**
* UI elements on the right are pushed offscreen 
* SortBy icon overlaps column header to the right of the currently sorted column

![image](https://github.com/ericvtheg/makid-public/assets/12592/5e8ab9e6-7ac6-4444-860a-832e4ea2525f)

**Comment by ltackett** [comment]
Some suggestions for how to address this issue:

> [The Chainsmokers 2 (Steve)](https://discord.com/channels/1174557402268450876/1174750842121883648/1174921304915312690)
> (1) You could have it so when the Name or Status textboxes are in focus, they "float" on top of the table, and the height of the box increases and covers some of the rows below it, so that you can see the whole note. 
> (2) You could just set them both to have fixed heights but be scrollable vertically.

**Comment by ltackett** [comment]
Another idea would be to truncate the text to the max-width of the cell, and reveal the full text in a scrollable [popover](https://developer.apple.com/design/human-interface-guidelines/popovers).


![](https://docs-assets.developer.apple.com/published/d8c60c58fb6bfe3b5e3cf88346e89abe/components-popover-intro~dark@2x.png)

**Comment by ericvtheg** [comment]
Fixed in upcoming version
