### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ltackett** [ericvtheg/makid-public#14]
This speaks for itself. 🧛‍♂️

> [patient wave](https://discord.com/channels/1174557402268450876/1174750842121883648/1174882816266346506)
> I am humbly going to put this request in early......DARK MODE 🌙

**Comment by ericvtheg** [comment]
sunset
<img width="1036" alt="Screenshot 2023-11-17 at 9 05 16 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/51eb892a-2027-4df5-9e80-5a7bb1417ddb">

forest
<img width="1038" alt="Screenshot 2023-11-17 at 9 06 08 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/7a75f6aa-2ce0-4800-9811-4a8861de6a1d">

dark
<img width="1083" alt="Screenshot 2023-11-17 at 9 06 41 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/84ea0b5c-afed-4687-a5a6-b5cbaed4a1ab">

halloween
<img width="1050" alt="Screenshot 2023-11-17 at 9 06 57 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/d15b036b-fb76-41af-b6c9-c3defa26dbb6">

coffee
<img width="1039" alt="Screenshot 2023-11-17 at 9 07 21 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/d6c7afe3-8ff0-40fa-9d1a-dcfff2e97c4c">

dim
<img width="1049" alt="Screenshot 2023-11-17 at 9 07 38 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/fd28e011-688c-4c5c-89a0-356e6cc45db9">

dracula
<img width="1049" alt="Screenshot 2023-11-17 at 9 07 55 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/26e7931e-eccf-41bb-82bf-8b25f7b14d10">

business
<img width="1045" alt="Screenshot 2023-11-17 at 9 08 16 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/7541f7ad-9a17-447f-9626-6b0c2cf3f8b7">

**Comment by ericvtheg** [comment]
Done. Added themes. Will be out in MAKID v0.0.8
<img width="1049" alt="Screenshot 2023-11-17 at 9 48 01 AM" src="https://github.com/ericvtheg/makid-public/assets/35897247/cdf3e19b-1e33-4353-8c7c-92df88c588ca">
