### ISSUE TITLE
[Filesystem] Unable to add projects on MacOS (Intel)

### ISSUE THREAD

**Issue by ltackett** [ericvtheg/makid-public#17]
> [Gorgons Gaze](https://discord.com/channels/1174557402268450876/1174750772416741426/1174851983266545754)
> I am using the intel mac version and The main window loads up but trying to add an ableton folder doesn't do anything.

Log: [main.log](https://github.com/ericvtheg/makid-public/files/13388721/main.log)

> [ericvtheg](https://discord.com/channels/1174557402268450876/1174750772416741426/1174853800851415070)
> Ok I see why. In the build process, there is a dependency that basically looks at what OS I'm on and generates the correct "code". This works fine for ARM64 macs cuz that's what I'm on. And it works fine on windows cuz I have a build step on windows.
>
> So I need to basically fix the build process to include that file

**Comment by ericvtheg** [comment]
Fixed in 0.1.0
