### ISSUE TITLE
Organize By Folder

### ISSUE THREAD

**Issue by ltackett** [ericvtheg/makid-public#2]
> [/u/RUUDIBOO](https://www.reddit.com/r/ableton/comments/17wcb5j/comment/k9gmgp1/)
> I'm working with a lot of different artists, over their career. This makes me end up with a huge cluster of projects of course, so it would be great if there would be the possibility to create my own folders. For me the first level would be artist, then in that artist folder would be their albums and projects, and within that I would store the songs. Best would be if it's not hardcoded to be artists and albums tho, but if users can just make their own flexible folder structure.

**Comment by ericvtheg** [comment]
Done!! v.0.2.0
