### ISSUE TITLE
[UI] Right click menu doesn’t popup in the correct position 

### ISSUE THREAD

**Issue by ltackett** [ericvtheg/makid-public#7]
**Environment:**
* All

**Steps to repro**
1. Have a large list of projects
2. Scroll down in the list
3. Right click anywhere on a project

**Expected behavior**
* The menu will popup relative to your cursor

**Actual behavior**
* The menu pops up further up in the viewport

**Additional Behaviors**
* Right clicking the Tier column appears to have no positional information and pops up in the top left

Video:
https://github.com/ericvtheg/makid-public/assets/12592/16d43942-e4ca-427f-8409-67fb3fe60917

![](https://github.com/ericvtheg/makid-public/assets/12592/16d43942-e4ca-427f-8409-67fb3fe60917)

![image](https://github.com/ericvtheg/makid-public/assets/12592/bb5fe56a-a4bb-43a8-a345-06e467d0349d)

**Comment by ericvtheg** [comment]
Fixed in 0.1.0
